import styled from "@emotion/styled";

export const QutionsCountStyles = styled("div")(({ theme }) => ({
  ".default-btn": {
    border: `1px solid ${theme.border.green}`,
    width: "30px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
  },
  ".MuiTypography-h5": {
    backgroundColor: theme.background.transparent,
    border: `none`,
    boxShadow: "none",
    borderRadius: "0px",
    color: theme.border.green,
    padding: "0px",
    height: "30px",
    fontSize: "1rem",
    cursor: "pointer",
  },
  ".active-btn": {
    backgroundColor: theme.background.green,
    border: `1px solid ${theme.background.green}`,
    width: "30px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
  },
  ".edited-btn": {
    backgroundColor: theme.background.yellow,
    border: `1px solid ${theme.background.yellow}`,
    width: "30px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
  },
  ".remove-btn": {
    backgroundColor: theme.background.red,
    border: `1px solid ${theme.background.red}`,
    width: "30px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
  },
}));
