export const PATH = {
  DASHBOARD: "/",
  REPORT:"/report",
  YEARMCQ:"/yearmcq",
  SUBJECTMCQ:"/subjectmcq",
  NONNURSING:"/nonnursing",
  MODELMOCK:"/modelmock",
  HYBRID:"/hybrid",
  PREMIUMPLANS:"/premiumplans",
  PLANDETAILS:"/plandetails",
  STANDARD:"/standard",
  PREMIUM:"/premium",
  TESTPAGE:"/testpage",
  ALERT:"/alert",
  DISCUSS:"/discuss",
  SETTINGS:"/settings",
  STUTB:"/stutb",
  PREMIUMTB:"/premiumtb",
  ADDMCQ:"/addmcq"
};
