export const PATH = {
  DASHBOARD: "/dashboard",
  REPORT: "/report",
  YEARMCQ: "/yearmcq",
  SUBJECTMCQ: "/subjectmcq",
  NONNURSING: "/nonnursing",
  MODELMOCK: "/modelmock",
  HYBRID: "/hybrid",
  PREMIUMPLANS: "/premiumplans",
  PLANDETAILS: "/plandetails",
  STANDARD: "/standard",
  PREMIUM: "/premium",
  TESTPAGE: "/testpage",
  ALERT: "/alert",
  DISCUSS: "/discuss",
  SETTINGS: "/settings",
  STUTB: "/stutb",
  PREMIUMTB: "/premiumtb",
  ADDMCQ: "/addmcq",
  UNBLOCK: "/unblock",
  STADD: "/stadd",
  PREADD: "/preadd",
  RECENTSTUDENT: "/recentstudent",
  YEARINSTITUTION: "/yearinstitution/:sno",
  SUBINSTITUTION: "/subinstitution/:sno",
  ADDSUB: "/addsub/:sno/:lastId",
  NONINSTITUTION: "/noninstitution/:sno",
  MODELINSTITUTION: "/modelinstitution/:sno",
  COURSE: "/course",
  UPDATEPLAN: "/updateplan/:planid",
  UPDATEDETAILS: "/updatedetails/:planid",
  ADDPREMIUMPLAN: "/addpremiumplan",
  PREMIUMPLANDETAILS: "/premiumplandetails",
  PASSWORDCHANGE: "/passwordchange",
  NOTIFICATION: "/notification",
  VIEWCOURSE: "/viewcourse/:sno",
  ADDCOURSE: "/addcourse",
  DAILYINSTITUTION: "/dailyinstitution",
  ADDQUESTION: "/addquestion",
  ADDNONNURSING: "/addnonnursing/:sno/:lastId",
  ADDMOCK: "/addmock/:sno",
  ADDMOCK1: "/addmock1/:sno/:id",
  ADDMCQ1: "/addmcq1",
  MCQTABLE: "/mcqtable",
  MCQTABLEPAGE: "/mcqtablepage/:id/:sno",
  UPLOADTEST: "/uploadtest/:sno/:id",
  ACHIEVEMENT: "/achievement",
  UPDATE: "/Update/:sno",
  ADDACHIEVEMENT: "/addachievement",
  UPDATECOURSE: "/updatecourse/:sno",
  NOTIFICATIONHISTORY: "/history",
  UPDATEADS: "/updateads",
  UPLOADTESTSUB: "/uploadtestsub/:sno/:lastId",
  UPLOADTESTMODEL: "/uploadtestmodel/:sno",
  SIGNIN: "/",
  OTP: "/otp",
  FORGET: "/forget", 
  UPLOADDAILYTEST: "/uploaddailytest/:sno",
  MINIINSTITUTION: "/miniinstitution",
  MINIUPLOAD: "/miniupload/:sno",
  MICROINSTITUTION: "/microinstitution",
  MICROUPLOAD: "/microupload/:sno",
  NONNURSINGMCQ: "/mcqnursingtable/:id/:sno",
  MOCKTABLEPAGE: "/mocktablepage/:id/:sno/:stageno",
  VIEWQUETIONSSUB: "/viewquestionssub/:id/:sno",
  VIEWQUESTIONSNURSING: "/viewquestionsnursing/:id/:sno",
  VIEWQUESTIONSMODEL: "/viewquestionsmodel/:id/:sno/:stageno",
  UPLOADTESTNURSING: "/uploadtestnursing/:sno/:lastId",
  BLOCKTABLEPRE: "/blocktablepre",
  HYBRIDVIEWTEST:"/hybridviewtest/:sno",
  MINITESTQUESTIONS:"/minitestquestions/:sno",
  MICROTESTQUESTIONS:"/microtestquestions/:sno",
  UPLOADQUESTION:"/uploadquestion/:sno/:id",
  AIIMSPRELIMS:"/aiims",
  PRELIMSCARD:"/prelimscard",
  PRELIMSINSTITUTION:"/prelimsinstitution/:sno",
  ADDPRELIMS:"/addprelims/:sno/:lastId",
  PRELIMSTABLE:"/prelimstablepage/:id/:sno",
  PRELIMSQUESTION:"/prelimsquestion/:id/:sno",
  MAINSCARD:"/mainscard",
  MAINSINSTITUTION:"/mainsinstitution/:sno",
  ADDMAINS:"/addmains/:sno/:lastId",
  MAINSTABLE:"/mainstablepage/:id/:sno",
  MAINSQUESTION:"/mainsquestion/:id/:sno",
  IMAGE:"/image"
};
